import { Navbar } from '@/components/navbar';
import { cn } from '@/lib/utils';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter, Nunito } from 'next/font/google';

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
});

const nunito = Nunito({
  variable: '--font-heading',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Aditya Kumar | Full Stack Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, nunito.variable, 'mx-auto font-sans antialiased')}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
